### PR TITLE
Rom table fix

### PR DESCRIPTION
**Pull request by c1728p9**
Fix intermittent LPC1768 crashes when parsing the ROM table.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
Can you review this @flit? This rebases and pulls in PR #253.

**Comment by flit** [comment]
LGTM

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
