### PR TITLE
Package reorganization

### PR DESCRIPTION
**Pull request by flit**
Reorganized and simplified target related package and module structure. Should make it easier to add new targets by reducing the number of files to edit. Separates framework modules from target-specific modules.

- Moved `target`, `coresight_target`, and `memory_map` to `pyOCD.core`.
- Moved `semihost` and `svd` to `pyOCD.debug`.
- Moved `flash_cortex_m`, `flash_kinetis`, and `target_kinetis` to `pyOCD.target.family`.
- Merged target-specific flash modules into target modules.
- Renamed target modules with CMSIS-Pack device names, unless the target does not have a pack available.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by flit** [comment]
cortex_test was failing for me due to the problem solved by #278. But it's strange that, for instance, #279 passed even though it doesn't have that fix. Not sure what's going on there.

**Comment by c1728p9** [comment]
Those two PRs have been merged, so if you rebase this I can give testing another try.

**Comment by flit** [comment]
@c1728p9 Rebased.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by flit** [comment]
@c1728p9 Thanks for rerunning the tests. I'm really curious why the cortex_test is failing.

**Comment by c1728p9** [comment]
It looks like its related to the software breakpoints:
```
 16:49:30 ------ Testing Software Breakpoints ------
16:49:30 Installed software breakpoint at 0x20000001
16:49:30 Exception 'module' object has no attribute 'target' when testing board 110000004420312054434a38313037313830303097969903
16:49:30 
```

**Comment by flit** [comment]
Thanks for looking into it!

**Comment by flit** [comment]
That commit should fix it. The problem was a reference to `pyOCD.target.target.Target` that moved to `pyOCD.core.target.Target`, in cortex_test itself.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
