### PR TITLE
Add support for RTL8195AM

### PR DESCRIPTION
**Pull request by v2422**
Add basic debugging operation support. Some tests over gdb are done. Flash is not supported yet.

### CODE REVIEW

**Comment by c1728p9** [comment]
Hi @v2422, do you have an mbed account?

**Comment by v2422** [comment]
Hi @c1728p9 ,

Just done. 
https://developer.mbed.org/users/RTK_Viller/

**Comment by c1728p9** [comment]
Before this PR can be merged the contributors agreement must be signed:
https://developer.mbed.org/contributor_agreement/

**Comment by v2422** [comment]
HI @c1728p9 ,

It's done now.

**Comment by c1728p9** [comment]
Thanks!

**Pull request merged**
