### PR TITLE
Enable read/write of FPU registers from GDB

### PR DESCRIPTION
**Pull request by adamgreen**
This PR request includes fixes for the issue that @c1728p9 encountered with my new code on his K22F device.

See commit messages for more details about this pull request.

### CODE REVIEW

**Comment by adamgreen** [comment]
I will probably add another commit to this PR later in the weekend to improve single stepping performance a bit more, especially for Cortex-M4F targets.

**Comment by c1728p9** [comment]
Does this patch effect single stepping performance?

**Comment by adamgreen** [comment]
@c1728p9 On a CPU without a FPU, the time should be the same but if you are running on a CPU with a FPU then it will be slower since GDB is going to send a 'g' packet to request all of the registers and now the FPU ones will be read as well.

The way to make single stepping faster in GDB is to return a 'T' response instead of a 'S' response to provide the debugger with just the registers it really needs to know: typically "sp, lr, and pc".

**Comment by c1728p9** [comment]
This patch fixes the problems I had with eclipse.  Eclipse also recognizes and displays the FPU registers.  This does make single stepping a little slower.  I would be very interested to see what kind of effect on speed this single stepping command has.  It looks like the vast majority of the time to step is being spent inside the 'g' command after a step - more than 85% (1.602s of 1.88s).  Below is some more detailed info.

Before Patch:
Step - 31 gdb commands, 0.811000109s to complete
Step - 30 gdb commands, 0.789000034s to complete

With patch
Step - 31 gdb commands, 1.900000095s to complete
Step - 30 gdb commands, 1.898000002s to complete

Stepping over a function in eclipse from start to end:
```
command 65 took 0.008000 at 1420952453.4: $s#73
command 66 took 0.200000 at 1420952453.6: $g#67
command 67 took 0.005000 at 1420952453.6: $m3048,4#9c
command 68 took 0.005000 at 1420952453.61: $m2ea0,4#f5
command 69 took 0.003000 at 1420952453.61: $Z1,2ea0,2#3d
command 70 took 0.031000 at 1420952453.64: $c#63
command 71 took 0.201000 at 1420952453.84: $g#67
command 72 took 0.005000 at 1420952453.85: $m2ea0,4#f5
command 73 took 0.003000 at 1420952453.85: $z1,2ea0,2#5d
command 74 took 0.008000 at 1420952453.86: $s#73
command 75 took 0.200000 at 1420952454.06: $g#67
command 76 took 0.007000 at 1420952454.07: $m2ea2,4#f7
command 77 took 0.011000 at 1420952454.08: $s#73
command 78 took 0.200000 at 1420952454.28: $g#67
command 79 took 0.006000 at 1420952454.28: $m2ea6,4#fb
command 80 took 0.010000 at 1420952454.29: $s#73
command 81 took 0.200000 at 1420952454.49: $g#67
command 82 took 0.005000 at 1420952454.5: $m2ea8,4#fd
command 83 took 0.009000 at 1420952454.51: $s#73
command 84 took 0.200000 at 1420952454.71: $g#67
command 85 took 0.005000 at 1420952454.71: $m2eac,4#28
command 86 took 0.009000 at 1420952454.72: $s#73
command 87 took 0.200000 at 1420952454.92: $g#67
command 88 took 0.007000 at 1420952454.93: $m2eae,4#2a
command 89 took 0.011000 at 1420952454.94: $s#73
command 90 took 0.201000 at 1420952455.14: $g#67
command 91 took 0.007000 at 1420952455.15: $m2eb2,4#f8
command 92 took 0.010000 at 1420952455.26: $m2e80,40#fc
command 93 took 0.008000 at 1420952455.27: $m2ec0,40#27
command 94 took 0.008000 at 1420952455.28: $m2f00,40#f5
command 95 took 0.000000 at 1420952455.28: $qL1200000000000000000#50
command 96 took 0.000000 at 1420952455.28: $qL1200000000000000000#50
```

**Comment by adamgreen** [comment]
Thanks again for the feedback.

I have started the T response change and it looks very promising.  With command line GDB, I see no 'g' commands being sent during single stepping.  I don't want to add it to this PR though since it isn't directly related to floating point register support itself and it would be best to consider it for merging on its own merits (or the lack thereof).  I will create a PR for it next week once I have done more testing.

**Comment by 0xc0170** [comment]
Adam, can you rebase this ?

Shouldn't we support 'p' / 'P' packet ? To read/write one register at the time

**Comment by adamgreen** [comment]
I will rebase later today.

My commit message addresses the 'p' packet command removal and the 'P' packet is still supported, even for floating point registers.

**Comment by adamgreen** [comment]
The rebase has been completed.

**Comment by adamgreen** [comment]
Thanks

**Comment by adamgreen** [comment]
@c1728p9 My 'T' response change which might help with single stepping performance can be found here:  https://github.com/adamgreen/pyOCD/compare/gdbTResponse  I am currently testing it before I issue a full PR.

**Comment by c1728p9** [comment]
I tried your 'T' response change locally and it looks like KDS still issues the g command after every step:
```
command 96 took 0.026000 at 1421897856.5: $s#73
command 97 took 0.005000 at 1421897856.51: $maa14,4#f4
command 98 took 0.005000 at 1421897856.51: $ma8b8,4#00
command 99 took 0.200000 at 1421897856.71: $g#67
command 100 took 0.003000 at 1421897856.71: $Z1,a8b8,2#48
command 101 took 0.023000 at 1421897856.74: $c#63
command 102 took 0.004000 at 1421897856.74: $ma8b8,4#00
command 103 took 0.200000 at 1421897856.94: $g#67
command 104 took 0.002000 at 1421897856.94: $z1,a8b8,2#68
command 105 took 0.027000 at 1421897856.97: $s#73
command 106 took 0.007000 at 1421897856.98: $ma8ba,4#29
command 107 took 0.203000 at 1421897857.18: $g#67
command 108 took 0.027000 at 1421897857.21: $s#73
command 109 took 0.007000 at 1421897857.22: $ma8be,4#2d
command 110 took 0.202000 at 1421897857.42: $g#67
command 111 took 0.027000 at 1421897857.44: $s#73
command 112 took 0.005000 at 1421897857.45: $ma8c0,4#f9
command 113 took 0.200000 at 1421897857.65: $g#67
command 114 took 0.026000 at 1421897857.68: $s#73
command 115 took 0.004000 at 1421897857.68: $ma8c4,4#fd
command 116 took 0.201000 at 1421897857.88: $g#67
command 117 took 0.026000 at 1421897857.91: $s#73
command 118 took 0.006000 at 1421897857.92: $ma8c6,4#ff
command 119 took 0.203000 at 1421897858.12: $g#67
command 120 took 0.027000 at 1421897858.15: $s#73
command 121 took 0.006000 at 1421897858.15: $ma8ca,4#2a
command 122 took 0.202000 at 1421897858.35: $g#67
command 123 took 0.007000 at 1421897858.41: $ma8c0,40#29
command 124 took 0.007000 at 1421897858.42: $ma900,40#f7
command 125 took 0.007000 at 1421897858.43: $ma940,40#fb
command 126 took 0.000000 at 1421897858.43: $qL1200000000000000000#50
command 127 took 0.000000 at 1421897858.43: $qL1200000000000000000#50
```

**Comment by adamgreen** [comment]
@c1728p9 Thanks for trying it out.  I guess I will shelve that idea for a bit then :)

It would be interesting to know if the unexpected 'g' commands originate directly from a single "next" command sent from Eclipse to GDB or if Eclipse is asking GDB to perform lower level "nexti" commands instead.

If I give GDB the "set remotelogfile pyocd.log" command before connecting to pyOCD then GDB logs the GDB client commands and the resulting packets transferred between GDB and pyOCD.  Here is what I see when I ask GDB to step over (using the GDB "next" command) a "wait(0.2)" command.

```
c next
w $s#73
r +$T050d:f01f0910;0e:d3010014;0f:7c010014;#4b
w +$m1400017c,4#8d
r +$00f028f9#ff
w +$s#73
r +$T050d:f01f0910;0e:81010014;0f:d0030014;#19
w +$m140003d0,4#89
r +$07ee100a#23
w +$m14000180,4#5b
r +$23696268#aa
w +$Z1,14000180,2#a3
r +$OK#9a
w +$c#63
r +$T050d:f01f0910;0e:c7030014;0f:80010014;#1e
w +$m14000180,4#5b
r +$23696268#aa
w +$m14000180,4#5b
r +$23696268#aa
w +$z1,14000180,2#c3
r +$OK#9a
w +
```

**Comment by c1728p9** [comment]
It seems like eclipse is sending a higher level step command and the GDB client is then issuing a series of step commands to the gdb server.  From the gdb trace in eclipse it looks like only 1 next command is being sent "-exec-next --thread 1 1" which performs the step over command (there are also several eclipse commands after this to read call stack info and disassemble the code around the pc).  The GDB client, and not eclipse, seems to be the one responsible for issuing repeated single step command followed by 'g'.

One thing I didn't realize when I was running my testing was that I had the compiler configured to generate code coverage (additional flags "-fprofile-arcs" and "-ftest-coverage").  This added extra assembly instructions to each line, which greatly contributed to the slower single stepping I was seeing.  Even with this off I see multiple 'g' commands, just not as many.

I also created a log of the single stepping like you suggested.  This was run with code coverage still turned on.   From the logs it looks like GDB single steps every instruction in the current function (issuing 'g' after each step) and only runs the continue command to step over the function call.

```
c 42-exec-next --thread 1 1
c next 1
w $s#73
r +$T050d:d8ff0020;0e:a1a80000;0f:78aa0000;#dd
w +$maa78,4#fe
r +$80b582b0#fb
w +$ma8a0,4#f7
r +$5c4bd3e9#63
w +$g#67
r +$00000000486aff1f0100000000000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff0020a1a8000078aa000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#1f
w +$Z1,a8a0,2#3f
r +$OK#9a
w +$c#63
r +$T050d:d8ff0020;0e:15ac0000;0f:a0a80000;#d5
w +$ma8a0,4#f7
r +$5c4bd3e9#63
w +$g#67
r +$00d0044004d004400000000005000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000a0a8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#b1
w +$z1,a8a0,2#5f
r +$OK#9a
w +$s#73
r +$T050d:d8ff0020;0e:15ac0000;0f:a2a80000;#d7
w +$ma8a2,4#f9
r +$d3e90223#fc
w +$g#67
r +$00d0044004d0044000000000486aff1f000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000a2a8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#94
w +$s#73
r +$T050d:d8ff0020;0e:15ac0000;0f:a6a80000;#db
w +$ma8a6,4#fd
r +$013243f1#c4
w +$g#67
r +$00d0044004d004400000000000000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000a6a8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#b2
w +$s#73
r +$T050d:d8ff0020;0e:15ac0000;0f:a8a80000;#dd
w +$ma8a8,4#ff
r +$43f10003#c1
w +$g#67
r +$00d0044004d004400100000000000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000a8a8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#b5
w +$s#73
r +$T050d:d8ff0020;0e:15ac0000;0f:aca80000;#08
w +$ma8ac,4#2a
r +$5949c1e9#0d
w +$g#67
r +$00d0044004d004400100000000000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000aca8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#e0
w +$s#73
r +$T050d:d8ff0020;0e:15ac0000;0f:aea80000;#0a
w +$ma8ae,4#2c
r +$c1e90223#f9
w +$g#67
r +$00d00440486aff1f0100000000000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000aea8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#88
w +$s#73
r +$T050d:d8ff0020;0e:15ac0000;0f:b2a80000;#d8
w +$ma8b2,4#fa
r +$00f00ff9#2b
w +$g#67
r +$00d00440486aff1f0100000000000000000000000000000000000000e8ff00200000000000000000000000200000000001010101d8ff002015ac0000b2a8000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#56
w +
c 43-break-list --thread-group i1
c info break
c 44-stack-info-depth --thread 1 11
c 45-break-list --thread-group i1
c info break
c 46-data-disassemble --thread 1 -s 43186 -e 43310 -- 1
w $ma880,40#fe
r +$44e0000080b588b004af624bd3e90023013243f100035f49c1e9002300f0ecf85c4bd3e90223013243f100035949c1e9022300f00ff9574bd3e90423013243f1#37
w +$ma8c0,40#29
r +$00035449c1e9042301204ff4e1311022fef7d2fe4f4bd3e90623013243f100034c49c1e906230a20f8f790fb03464a481946fef777ff474bd3e90823013243f1#35
w +$ma900,40#f7
r +$00034449c1e9082303f0c6fa414bd3e90a23013243f100033e49c1e90a230023009300230193002302933c4b03933c483c494ff440523c4b03f080fa0346fb73#d2
w +
c 47-list-thread-groups
w $qL1200000000000000000#50
r +$#00
w +
c 48-thread-info 1
w $qL1200000000000000000#50
r +$#00
w +
```

**Comment by adamgreen** [comment]
@c1728p9 Thanks for the additional information.  It shows that Eclipse isn't responsible and the problem lies in GDB.  Now I just need to figure out what is different about our GDB scenarios since in mine GDB doesn't issue the 'g' command after the step commands except when it steps into a function and it wants to run until returning from that function call.

What toolchain are you running?  Maybe I can try running my test with your build of GDB.  I am currently using GCC ARM Embedded 4.9-2014-q4-major.

Thanks again,

Adam

**Comment by c1728p9** [comment]
I was running the one that comes with KDS_1.1.1, but I re-tested with 4.9 2014q4 and saw the same thing.  Maybe it is a problem with the MI command set eclipse uses.

**Comment by adamgreen** [comment]
If something like a frame pointer was being used in your code then my list of important registers in the T response might be missing a register that GDB wants to see for your code.  You could try adding some more registers to the T response.  Currently I return sp, lr, and pc (r13-r15):
```python
    def getTResponse(self, gdbInterrupt = False):
        # ...
        # Append sp(r13), lr(r14), pc(r15)
        response += self.getRegIndexValuePair(13)
        response += self.getRegIndexValuePair(14)
        response += self.getRegIndexValuePair(15)
```

You could try adding a few more registers to this list, such as r11 and r12 since they are sometimes used to setup a stack frame.  I removed the -fomit-frame-pointer option from my build but it still generated similar code as before and I still got the expected single stepping behavior.

By the way I am just single stepping through the loop in the basic blinky sample:
```c++
#include "mbed.h"

DigitalOut myled(LED1);

int main()
{
    while(1)
    {
        myled = 1;
        wait(0.2);
        myled = 0;
        wait(0.2);
    }
}
```

I should try to install KDS to reproduce your problem.

**Comment by c1728p9** [comment]
Good call with the frame pointer. I added the -fomit-frame-pointer compiler flag to my code, and stepping went from ~2.0 seconds to ~0.4s. I do not see any 'g' commands being sent when this is the case. I also see similar performance if I add r7 (which appears to be the frame pointer) to the T response as you suggested. Do you know if cortex-m's have a recommended frame pointer, or if r7 is just the frame pointer by chance? If r7 is the recommended frame pointer, then it would probably be good to add this. Maybe it should be added regardless. Let me know what you think.

Also, if you wanted to try out KDS, it is free. There is a good user interface, so you can set breakpoints and step directly from the c file you were working on. Alternatively, you could use Eclipse with OpenOCD plugin from GNU ARM Eclipse (this is the same configuration that KDS uses).

Thanks again for looking at this issue with the great detail you did. This will make eclipse performance far, far better :).

**Comment by adamgreen** [comment]
Thank you!  Thank you!

I finally figured out that with GCC_ARM that I had to add the -fno-omit-frame-pointer flag to get the same frame pointer issue whereas I had only tried deleting the existing -fomit-frame-pointer option the night before.  Once I switched to that flag, I was able to reproduce your problem and test your R7 addition.  I just issued a PR https://github.com/mbedmicro/pyOCD/pull/98 with the latest 'T' response change.

**Comment by 0xc0170** [comment]
Great cooperation ! Very pleased to see to narrow this down to a frame pointer issue.

**Pull request merged**
