### PR TITLE
Fixed MemoryMap for K82F, inaccessible RamRegion was defined that cau…

### PR DESCRIPTION
**Pull request by linlingao**
…sed DAPLink MSD test to fail

### CODE REVIEW

**Comment by flit** [comment]
@linlingao How does DAPLink MSD test access the RamRegions? I would much rather fix this by changing the test so it doesn't attempt to access regions without backing physical memory. Maybe also change pyOCD to explicitly call out internal RAMs.

The reason for wanting to address this issue differently is that the memory regions in CMSIS-Packs may include all architectural memory regions, whether or not there is a physical memory backing that region.

**Comment by linlingao** [comment]
@flit DAPLink finds the first region with the type == 'ram' in memory_map. 
  ram_regions = [region for region in memory_map if region.type == 'ram']
  ram_region = ram_regions[0]
 we can come up with a way to distinguish the internal RAM from the rest in pyOCD, it would work. Keep in mind that if you add an identifier to this target, you would have to add identifier to all targets.

**Pull request merged**
