### PR TITLE
Add support for LPC54608

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahadevan Mahesh <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@c1728p9 Can this be integrated into pyOCD. The DAPLink support is also available.

**Comment by mmahadevan108** [comment]
@c1728p9 Anything else needed for this PR?

**Comment by mmahadevan108** [comment]
Can this be merged?

**Comment by c1728p9** [comment]
Hi @mmahadevan108 please run the automated tests locally on this target. To run these use the command ```python test/automated_test.py```. I'm seeing some failures on the LPC54608 when I run it locally.

**Comment by mmahadevan108** [comment]
Hi @c1728p9. I have updated the commit to pass the automated_tests

**Comment by mmahadevan108** [comment]
Hi @c1728p9. Can you take a look at this update and let me know if anything is needed for this PR.

**Comment by mmahadevan108** [comment]
Hi @c1728p9 . Can this be merged into the mainline

**Pull request merged**
