### PR TITLE
Move C sources to common folder

### PR DESCRIPTION
**Pull request by flit**
Moved the C code in the `pyOCD/flash/analyzer` and `test/gdb_test_program` folders to a top-level `src` folder.

### CODE REVIEW

**Comment by c1728p9** [comment]
(CI is down so I'm running it locally for now)

**Comment by flit** [comment]
Thanks. I've always had issues running the gdb tests (it hangs), but I'll take a look.

**Comment by flit** [comment]
Rebased and fixed GDB test.

**Comment by c1728p9** [comment]
@flit Please rebase this PR so I can re-trigger testing

**Comment by studavekar** [comment]
Can one of the admins verify this patch?

**Comment by flit** [comment]
@c1728p9 Rebased.

**Pull request merged**
