### PR TITLE
Register and memory caching

### PR DESCRIPTION
**Pull request by flit**
There are separate register and memory cache classes. A `CachingDebugContext` ties them together in a debug context so the GDB server can access the target through the caches. Includes a new unit test for the memory cache.

### CODE REVIEW

**Comment by c1728p9** [comment]
I'm getting this error when in the gdb test:
```
ERROR:root:Unhandled exception in handleMsg: 'CortexM' object has no attribute 'run_token'
```

**Comment by flit** [comment]
Ah, thanks. That's a rebase mistake. I forgot the register cache was dependant on a change from the RTOS branch, and I was moving around and rebasing branches so much yesterday I guess I forgot what I did and didn't test on boards. I'll have to rebuild this branch to include 4f6de62 from the RTOS PR. Sorry for the confusion!

**Comment by flit** [comment]
Don't bother rerunning tests, there is another test failure. I was just rebasing.

**Comment by c1728p9** [comment]
Since #242 was merged can this be rebased?

**Comment by studavekar** [comment]
Can one of the admins verify this patch?

**Comment by flit** [comment]
Yes, I'll rebase it no later than this weekend.

**Comment by flit** [comment]
@c1728p9 Rebased.

**Comment by c1728p9** [comment]
This is failing  Cortex Test and Gdb Test for all targets.

**Comment by flit** [comment]
@c1728p9 Rebased, fixed failing tests, added a register cache unit test, and did some refactoring. Should be ready to go.

**Comment by flit** [comment]
@c1728p9  Is this PR ready to be merged?

**Pull request merged**
