### PR TITLE
Fix a typo in gdb command handler table.

### PR DESCRIPTION
**Pull request by Hsiangkai**
'c' for "continue at addr" and 'C' for "continue with signal".

### CODE REVIEW

**Comment by c1728p9** [comment]
Hi @Hsiangkai, what kind of problem was this causing?

**Comment by c1728p9** [comment]
CC: @flit

**Comment by Hsiangkai** [comment]
I just reviewed source code and found these typo. There is no functional problem about the modification.

**Comment by Hsiangkai** [comment]
@c1728p9 Do you know why Tarvis CI build is pending? I saw that "Done. Your build exited with 0.
" in build log.

**Pull request merged**
