### PR TITLE
Handle unsupported boards gracefully along with micro:bit support

### PR DESCRIPTION
**Pull request by c1728p9**

### CODE REVIEW

**Comment by c1728p9** [comment]
test this please

**Comment by c1728p9** [comment]
test this please

**Comment by c1728p9** [comment]
test this please

**Comment by 0xc0170** [comment]
+1, however dont have access to CI at the moment to see the failure

**Comment by c1728p9** [comment]
test this please

**Comment by c1728p9** [comment]
test this please

**Comment by c1728p9** [comment]
test this please

**Pull request merged**
