### PR TITLE
New Kinetis targets and some fixes

### PR DESCRIPTION
**Pull request by flit**
New targets:
- K28F
- KL82Z
- KW41Z
- K22FA12

Fixes:
- Corrected FRDM-KL28ZEM and HVP-KE18F board IDs.
- Fixed issue with KL28T primary core memory map.
- Fixed some problems with K82F support.

Note that the K22FA12 target is a non-board target (the first one).

### CODE REVIEW

**Comment by studavekar** [comment]
Can one of the admins verify this patch?

**Comment by c1728p9** [comment]
@flit please rebase this PR

**Comment by flit** [comment]
@c1728p9 Rebased.

**Pull request merged**
