### PR TITLE
Board listing improvements

### PR DESCRIPTION
**Pull request by flit**
- Moved board ID table into a separate file for easier maintenance.
- Improved the command line board selection interface by colorizing. Listing is also sorted by board name, so the boards always have the same numbers.
- Board ID matching for the "--board" argument for tools uses a contains match now instead of requiring the entire board ID.

### CODE REVIEW

**Comment by flit** [comment]
Strange… the Travis build segfaulted during the semihosting test.

**Comment by c1728p9** [comment]
Hi @flit I retriggered the travis job twice and it segfaulted both times, so this isn't an intermittent failure.

**Comment by flit** [comment]
Very odd. It's not just this PR that is failing with the segfault, it seems to be every recent build.

**Pull request merged**
