### PR TITLE
Fix breakpoints

### PR DESCRIPTION
**Pull request by c1728p9**
Allow debugging generic cortex_m devices without a memory map present. Also improve handling when out of breakpoints.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@flit, this fixes some problems with breakpoints. If you don't mind could you give it a quick review?

**Comment by MarceloSalazar** [comment]
Tested on an unsupported platform (beetle) and works great!
It's important to build with symbols and update the target with the corresponding binary (otherwise symbols won't match).

Minor suggestion: this message shown in the gdb_server console could be changed into a WARNING, so people don't get confused:
`ERROR:root:Unsupported board found 5003`

Thanks @c1728p9!

**Comment by flit** [comment]
@MarceloSalazar I agree with your suggestion about changing the unsupported board message to a warning.

**Comment by flit** [comment]
@c1728p9 LGTM. Sorry I didn't get to it until after you merged!

**Pull request merged**
