### PR TITLE
Adding Cython as a setup dependency for Mac

### PR DESCRIPTION
**Pull request by bridadan**
Adds Cython as a setup_requires dependency on Mac, solving some dependency issues.

### CODE REVIEW

**Comment by c1728p9** [comment]
Looks good to me.  This should fix #163

**Comment by posborne** [comment]
:+1:

**Comment by c1728p9** [comment]
Should this pull request be reverted since this bug has been fixed in hidapi?
https://github.com/trezor/cython-hidapi/pull/18

**Comment by bridadan** [comment]
Probably :)

**Comment by 0xc0170** [comment]
Great news, cython fixed.

**Pull request merged**
