### PR TITLE
Cleanup and refactor

### PR DESCRIPTION
**Pull request by c1728p9**
Refactor code to make it match pep8 more closely, along with fixing errors, and re-scoping module level constants into their respective classes.

### CODE REVIEW

**Comment by c1728p9** [comment]
Unit tests pass

Automated tests pass:
```
------ Speed Test Performance ------
Target    Write Speed     Read Speed      USB speed       USB overlap speed

kl46z     42.172461 KB/s  43.924930 KB/s  31.334450 KB/s  59.959747 KB/s
nrf51     12.780031 KB/s  12.800000 KB/s  15.968811 KB/s  16.001953 KB/s
k22f      50.921521 KB/s  51.160035 KB/s  31.836775 KB/s  63.627186 KB/s
lpc800    24.824248 KB/s  24.674715 KB/s  31.515267 KB/s  31.371949 KB/s
lpc11u24  19.645081 KB/s  20.582914 KB/s  31.591226 KB/s  63.442401 KB/s



------ Analyzer Performance ------
Target    Analyzer    Rate              Time

kl46z     CRC32       1069.976010 KB/s  0.244999885559 s
nrf51     CRC32       621.194063 KB/s   0.422000169754 s
k22f      CRC32       1224.972039 KB/s  0.427999973297 s
lpc800    CRC32       348.594486 KB/s   0.047000169754 s
lpc11u24  PAGE_READ   799.217021 KB/s   0.0410001277924 s



------ Test Rate ------
Target    Chip Erase          Page Erase          Page Erase (Same data)

kl46z     18.840305 KB/s      15.252458 KB/s      40.876969 KB/s
nrf51     9.272541 KB/s       6.706337 KB/s       12.469391 KB/s
k22f      26.673178 KB/s      22.347215 KB/s      46.278401 KB/s
lpc800    11.237310 KB/s      4.860279 KB/s       20.844783 KB/s
lpc11u24  11.453338 KB/s      8.825209 KB/s       18.326621 KB/s



------ TEST RESULTS ------
Target         Test           Result         Time

kl46z          Basic Test     Pass           3.84899997711
kl46z          Speed Test     Pass           14.3259999752
kl46z          Cortex Test    Pass           3.1130001545
kl46z          Flash Test     Pass           58.010999918
nrf51          Basic Test     Pass           4.41000008583
nrf51          Speed Test     Pass           39.7179999352
nrf51          Cortex Test    Pass           6.16300010681
nrf51          Flash Test     Pass           117.545000076
k22f           Basic Test     Pass           3.50699996948
k22f           Speed Test     Pass           21.9019999504
k22f           Cortex Test    Pass           4.26200008392
k22f           Flash Test     Pass           72.9479999542
lpc800         Basic Test     Pass           4.09200000763
lpc800         Speed Test     Pass           9.53100013733
lpc800         Cortex Test    Pass           2.95799994469
lpc800         Flash Test     Pass           13.6349999905
lpc11u24       Basic Test     Pass           7.33100008965
lpc11u24       Speed Test     Pass           8.875
lpc11u24       Cortex Test    Pass           4.17899990082
lpc11u24       Flash Test     Pass           21.3199999332

Test Time: 421.678999901
All tests passed
```

**Comment by pmaupin** [comment]
Three observations from the left-field peanut gallery:

1) It is much better to separate changes by function.

2) This is particularly true when doing both functional changes and PEP8 changes.  It is _extremely_ hard for others to follow which is which.

3) When I had some code dumped on me that didn't follow this practice, I modified some code I had to be able to cope.  If you clone the current version of [astor](https://github.com/berkerpeksag/astor/), then you can do `python -m astor.rtrip <dirname>` and it will create a temporary directory named tmp_rtrip, that contains the code that has been compiled into an AST and then decompiled.  It is extremely easy to compare two such directories to insure that your PEP-8 changes didn't change anything else.

**Comment by c1728p9** [comment]
Thanks for the feedback @pmaupin .  I agree that cosmetic changes should be separate from functional changes.  For that reason this pull request has one commit for the cosmetic pep8 changes only.   If you would prefer the cosmetic changes be in a separate pull request, let me know and I'll create one.

Also, thanks for sharing the info about astor.  This will be an extremely useful tool for verifying cosmetic changes.  I ran this before and after the commit which auto-formatted the code and found a typo on my part.  I updated the pull request to fix that.  With this latest pull request the commit with cosmetic changes generates the same output as before when running astor.rtrip.

**Comment by 0xc0170** [comment]
I was going to write something similar to the comment above. I prefer feature-complete PR. This could be split to at least 2 separate PR (merges). Its fine for now if you don't insist of splitting this. I'll have closer look at those functional changes tomorrow morning :wink:

**Comment by 0xc0170** [comment]
LGTM

**Pull request merged**
