### PR TITLE
Add support for GigaDevice

### PR DESCRIPTION
**Pull request by MikeXiaoshi**

### CODE REVIEW

**Comment by flit** [comment]
Hi @MikeXiaoshi, what is your mbed user account name? Have you signed the [Mbed Contributor License Agreement](https://os.mbed.com/contributor_agreement/)? Thanks!

**Comment by MikeXiaoshi** [comment]
Hi @flit , I have no mbed user account. I will apply for one as soon as I can. Thanks a lot.

**Comment by flit** [comment]
@MikeXiaoshi Have you had a chance to sign the Contributor License Agreement?

**Comment by flit** [comment]
Ok, no worries. Btw, I'm about to merge in preliminary CMSIS-Pack support, so GigaDevice chips can be supported if the user provides a pack.

**Comment by flit** [comment]
Closing due to inactivity.

**Pull request closed without merging**
