### PR TITLE
Add support for RedBearLab-BLE-Nano2 and Seeed 96Boards Nitrogen

### PR DESCRIPTION
**Pull request by rsalveti**

### CODE REVIEW

**Comment by rsalveti** [comment]
Travis CI failure seems unrelated:
pyOCD/test/test_semihosting.py /home/travis/.travis/job_stages: line 57:  2562 Segmentation fault      (core dumped) py.test pyOCD/test

**Comment by rsalveti** [comment]
Travis CI build still failing, any update?

**Comment by flit** [comment]
Closing since I fixed conflicts in PR #358.

**Pull request closed without merging**
