### PR TITLE
Add support for the Embedded Planet EP_AGORA board

### PR DESCRIPTION
**Pull request by trowbridgec**
This PR adds support to the Embedded Planet `EP_AGORA` board.

### CODE REVIEW

**Comment by trowbridgec** [comment]
@maclobdell @loverdeg-ep @farrenv @AGlass0fMilk @millerc-ep

**Comment by 40Grit** [comment]
@flit

**Comment by flit** [comment]
My apologies for missing this earlier!

**Comment by 40Grit** [comment]
Any chance or value in getting a minor release with this in it?

**Pull request merged**
