### PR TITLE
Fix resume, prevent stepping into interrupts and add hard fault vector catch

### PR DESCRIPTION
**Pull request by c1728p9**
When using GDB, a typical way of moving the execution address is to set
a breakpoint with the command 'break [line]' and then jump to that
address with the command 'jump [line]'.  This does not work because
the function maybeSkipBreakpoint will cause GDB to skip the breakpoint.
This patch fixes that problem by removing the function
maybeSkipBreakpoint.

GDB single stepping still works as expected and does not get stuck
when trying to step over breakpoints.  This is because the GDB
client automatically removes the breakpoint when stepping over it
and restores it after.

When using Eclipse as a GDB front end this fixes the problem where
where "Move to line" causes the device to begin executing code,
rather than just moving the PC.

### CODE REVIEW

**Comment by adamgreen** [comment]
What happens now if you try to step over code which actually has a hard coded breakpoint in the machine code?

**Comment by c1728p9** [comment]
If you try to step over a breakpoint in flash you will always halt at the breakpoint and will not be able step over it.  This was the same behavior before my patch.  The function maybeSkipBreakpoint only checks hardware breakpoints.

**Comment by c1728p9** [comment]
Verified basic_test.py still runs without problems on a K22F freedom board.

**Comment by adamgreen** [comment]
There are some very cool commits in this PR.

I tried it on my LPC1768 with no problems.  On my NRF51822 I couldn't use the "load" command from within GDB.  When I do, it gets into an infinite loop between your various reset routines.  Here is a snippet of the callstack:
```
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/target_nrf51822.py", line 73, in resetStopOnReset
    CortexM.resetStopOnReset(self, True)
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/cortex_m.py", line 652, in resetStopOnReset
    self.reset(software_reset)
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/target_nrf51822.py", line 46, in reset
    self.resetStopResume()
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/target_nrf51822.py", line 53, in resetStopResume
    self.resetStopOnReset()
  File "/usr/local/lib/python2.7/dist-packages/pyOCD/target/target_nrf51822.py", line 73, in resetStopOnReset
    CortexM.resetStopOnReset(self, True)
```

**Comment by c1728p9** [comment]
Thanks for testing and good catch.  I updated the PR to fix the NRF51822.  Unfortunately I don't have a NRF51822 development board so I am unable to run the fix to confirm it works.  Could you give it another try and let me know if it fixes the problem?

**Comment by adamgreen** [comment]
Yep, that fixed the "load" issue on my NRF51822 board.

Thanks!

**Comment by c1728p9** [comment]
This pull request should be ready to merge unless anyone wants changes to it.

**Comment by 0xc0170** [comment]
@c1728p9 
Thanks, I have this in my queue for review/merge.

**Comment by c1728p9** [comment]
Excellent, just making sure no one was waiting on me.

**Pull request merged**
