### PR TITLE
Added targets HC32F46x, HC32F120 and HC32M120 of HDSC MCU

### PR DESCRIPTION
**Pull request by lennvn**
Added targets HC32F46x, HC32F120 and HC32M120 of HDSC MCU.

### CODE REVIEW

**Comment by flit** [comment]
Thanks for the pull request!

**Comment by lennvn** [comment]
Hi，Chris. This is my first time contributing code on a Python open source project and I really can't find a way to solve this problem. Could you please tell me the details of the failure of the morph test? Thank you very much.

**Comment by flit** [comment]
My apologies for not getting back to you earlier. The test failure is not caused by your changes as far as I can tell (we're seeing some intermittent test failures).

Please rebase (don't merge from master) to correct the conflicts and it's ready to go. You'll have to force push after you rebase, which will allow reusing this PR.

**Pull request closed without merging**
