### PR TITLE
Auto-detection of STLink targets

### PR DESCRIPTION
**Pull request by flit**
This brings in support for auto-detection of the target associated with on-board STLinkV2-1 probes, so it works just as transparently as with DAPLink. Also brought in the list of ST board IDs from mbed-os-tools.

### CODE REVIEW

**Comment by jeromecoutant** [comment]
Hi
It seems that this re-implements mbedls ?
Can we imagine that pyOCD reuse mbedls board id table ?

**Comment by flit** [comment]
Yes, it uses a highly stripped-down version of the mbed-ls (aka mbed-os-tools) code. The main reason for not reusing the original code was because it does a lot of other checks, and supports other probes. By removing these features we can make it simpler and faster.

Unfortunately we can't reuse the mbed-ls platform table because it doesn't contain the target type or test binary name that pyOCD needs. However, we're looking at adding this information to the Mbed platforms database, so pyOCD (and mbed-ls) can download it at runtime.

**Comment by flit** [comment]
Fyi, the only CI tests that failed were known issues with STM32 devices, like #579.

**Comment by jeromecoutant** [comment]
Can we still use a target not defined in this board_ids list ?

**Comment by flit** [comment]
Yes, of course! The `--target` argument and `target_overide` user option are still available.

**Pull request merged**
