### PR TITLE
Fix travis failures

### PR DESCRIPTION
**Pull request by c1728p9**
Pin the cmsis-svd version to 0.1 since version 0.2 and 0.3 cause
installation problems in some configurations.

### CODE REVIEW

**Comment by c1728p9** [comment]
@flit will this older version still provide all the necessary svd files?

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by flit** [comment]
Any idea what configs and why it fails installation?

The main problem with v0.1 is that most or all files have an `.xml` extension, while newer releases switched to `.svd`. pyOCD uses `.svd`.

Is there a way to override the cmsis-svd version used only for Travis? If the specified SVD file isn't found, it won't cause a fatal error.

**Comment by flit** [comment]
Looks like v0.2 includes the [extension rename](https://github.com/posborne/cmsis-svd/commit/9f2ca607848e5b368f89e0888a0e13c7b43cf764).

**Comment by c1728p9** [comment]
@flit, this could also cause problems to user, which is why I was concerned.  I suspect it is related to cmsis-svd's setup dependencies:
```
    setup_requires=[
        'setuptools-markdown>=0.1',
    ],
```

**Comment by 0xc0170** [comment]
cmsis-svd was fixed, we might test that one and reconsider this PR?

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
