### PR TITLE
Fixed a bug of HC32x120 flash algorithm. Added OTP program algorithm …

### PR DESCRIPTION
**Pull request by lennvn**

### CODE REVIEW

**Comment by flit** [comment]
Fyi, it is best to force push your branch after rebasing. This will reuse the same pull request, so you don't need to create a new one.

**Comment by flit** [comment]
I'm working on a change right now to store the SVD data as individual XML files in the git repo, so we don't have these frequent merge conflicts caused by `svd_data.zip`. You probably want to wait until I merge this change before rebasing this PR. Sorry for continued conflicts/rebasing, this should be the last!

**Comment by flit** [comment]
Please see #799 for the change mentioned above.

**Comment by lennvn** [comment]
Thank you very much, Chris.
I rebased the latest commit, fixed the conflicts, and force pushed. Hop it works. If not, please tell me the details of the failure.

**Pull request merged**
