### PR TITLE
Merge command line tools

### LINKED ISSUE #448: Merge command line tools
Combined the three pyOCD command lines tools (pyocd-tool, pyocd-gdbserver, and pyocd-flashtool) into a single `pyocd` tool with multiple subcommands. This will make it much easier to release a binary distribution.

### PR DESCRIPTION
**Pull request by flit**
This pull request combines the three legacy command line tools into a new `pyocd` tool with subcommands for the existing functionality. The tool is implemented as the `pyocd.__main__` module, so pyOCD can now be invoked by running `python -mpyocd`.

Usage:
```
usage: pyocd [-h] [-V] [--help-options]  ...

PyOCD debug tools for Arm Cortex devices

optional arguments:
  -h, --help      show this help message and exit
  -V, --version   show program's version number and exit
  --help-options  Display available session options.

subcommands:
  
    commander     Interactive command console.
    cmd           Alias for 'commander'.
    erase         Erase entire device flash or specified sectors.
    flash         Program an image to device flash.
    gdbserver     Run the gdb remote server(s).
    gdb           Alias for 'gdbserver'.
    json          Output information as JSON.
    list          List information about probes, targets, or boards.
```

Command line arguments have been normalized across tools. They are generally compatible with legacy tools, but there are some changes. Also, some of the more esoteric options have had their command line arguments dropped in favour of the generic method of setting session options.

The biggest argument change is that `--board` no longer selects the debug probe. That is now handled by `--uid`, with `--board` reserved for future selection of board name (like `--target`, but for boards).

The erase functionality previously in `pyocd-flashtool` has been extracted into the `erase` subcommand.

Features that were previously implemented directly as part of the legacy tools has been refactored into reusable modules: programming bin, hex, or elf files into flash, chip and sector erasing, hex dumps, and generating dictionaries for JSON output.

The three legacy tools now output a warning that they are deprecated.

As part of this change, pyOCD will look for and load a `pyocd.yaml` or `pyocd.yml` config file in the working directory.

Fixes #448.
Closes #395.

### CODE REVIEW

**Comment by flit** [comment]
@arekzaluski Fyi, this PR include the board listing functionality in #395.

**Comment by flit** [comment]
cc @MaureenHelm

**Comment by flit** [comment]
fixes #448

**Comment by flit** [comment]
Rebased and squashed.

**Comment by arekzaluski** [comment]
Looks really good. I've done quick testing and I enjoy being able to run all commands using single tool. I haven't yet looked at the code. I'm only missing `reset` command that we are using from `pyocd-tool`.

**Comment by flit** [comment]
Thanks for taking it for a test drive.

You actually helped me discover a bug! You should should be able to reset the target by running `pyocd cmd -c reset`. Similar for any other of the interactive commands. However, it was not correctly splitting commands provided this way: `pyocd cmd -c 'rw 0 8'` did not work.

**Pull request merged**
