### PR TITLE
[RT1050] fix reset catch for flash target

### PR DESCRIPTION
**Pull request by jhqian**
- Enable reset catch for flash target by adding HW breakpoint to reset
handler for flash target (XIP).

Signed-off-by: Ryan QIAN <jianghao.qian@nxp.com>

### CODE REVIEW

**Comment by jhqian** [comment]
Hi @flit , could you please help to check this PR? Thanks in advance.

**Comment by flit** [comment]
Hi @jhqian, really sorry I didn't notice this PR! (You can ping me directly via email if you like.)

**Comment by jhqian** [comment]
> Hi @jhqian, really sorry I didn't notice this PR! (You can ping me directly via email if you like.)

Sure, will do next time : )

**Pull request merged**
