### PR TITLE
Update code to use the pyDAPAccess submodule

### PR DESCRIPTION
**Pull request by c1728p9**
Remove pyDAPAccess from pyOCD and instead rely on the pyDAPAccess
package.

### CODE REVIEW

**Comment by 0xc0170** [comment]
We don't want to rely on more strict semver on pyDAPAccess? >=0.1.0, <0.2.0 ?

**Comment by c1728p9** [comment]
Sounds good to me, especially since pyDAPAccess is below 1.0.0

**Comment by tgarc** [comment]
So from what I gather pyDAPAccess has become it's own module which you've released on pypi. But the repository for this is not yet up? What made you decide to split from the pyOCD package?

**Comment by c1728p9** [comment]
Don't worry, the repository will be up before this patch is merged.  Split the pyOCD package to keep things modular and to make a cleaner interface for the pyOCD backend.

**Comment by 0xc0170** [comment]
Bump, what's the status?

**Comment by c1728p9** [comment]
This PR is on hold until pyDAPAcccess is officially released

**Comment by c1728p9** [comment]
test this please

**Comment by c1728p9** [comment]
test this please

**Pull request closed without merging**
